apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base/

images:
  - name: order-service
    newName: us-central1-docker.pkg.dev/retailhub-services/retailhub/order-service
    newTag: dev
  - name: payment-service
    newName: us-central1-docker.pkg.dev/retailhub-services/retailhub/payment-service
    newTag: dev
  - name: product-service
    newName: us-central1-docker.pkg.dev/retailhub-services/retailhub/product-service
    newTag: dev
  - name: user-service
    newName: us-central1-docker.pkg.dev/retailhub-services/retailhub/user-service
    newTag: dev
  - name: loyalty-service
    newName: us-central1-docker.pkg.dev/retailhub-services/retailhub/loyalty-service
    newTag: dev
