apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-service
  namespace: dev
  labels:
    app: loyalty-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty-service
  template:
    metadata:
      labels:
        app: loyalty-service
    spec:
      containers:
      - name: loyalty
        image: us-central1-docker.pkg.dev/retailhub-services/retailhub/loyalty-service:dev-7523ed5
        imagePullPolicy: Always
        ports:
        - containerPort: 5006
        livenessProbe:
          httpGet:
            path: /health
            port: 5006
          initialDelaySeconds: 10
          periodSeconds: 10
