apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-service
  namespace: dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: loyalty-service
  template:
    metadata:
      labels:
        app: loyalty-service
    spec:
      serviceAccountName: loyalty-service
      imagePullSecrets:
      - name: gcr-json-key
      containers:
      - name: loyalty
        image: loyalty-service
        imagePullPolicy: Always
        ports:
        - containerPort: 5006
        livenessProbe:
          httpGet:
            path: /health
            port: 5006
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5006
          initialDelaySeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
