apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      serviceAccountName: payment-service
      imagePullSecrets:
      - name: gcr-json-key
      containers:
      - name: payment
        image: payment-service
        imagePullPolicy: Always
        ports:
        - containerPort: 5004
        livenessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
