apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: dev
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment
        image: us-central1-docker.pkg.dev/retailhub-services/retailhub/payment-service:dev-7523ed5
        imagePullPolicy: Always
        ports:
        - containerPort: 5004
        livenessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 10
          periodSeconds: 10
