apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: dev
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product
        image: us-central1-docker.pkg.dev/retailhub-services/retailhub/product-service:dev-7523ed5
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        livenessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 10
          periodSeconds: 10
