name: Deploy to QA

on:
  push:
    branches: [ qa ]

permissions:
  contents: read
  id-token: write

env:
  GCP_PROJECT_ID: retailhub-services
  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/427578819714/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider
  GCP_SERVICE_ACCOUNT: github-actions@retailhub-services.iam.gserviceaccount.com
  ARTIFACT_REGISTRY: us-central1-docker.pkg.dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
    - uses: google-github-actions/setup-gcloud@v2
    - run: gcloud auth configure-docker ${{ env.ARTIFACT_REGISTRY }}
    - run: |
        for service in order payment loyalty user product; do
          docker build -t ${{ env.ARTIFACT_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/retailhub/$service:qa-${{ github.sha }} $service-service/
          docker push ${{ env.ARTIFACT_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/retailhub/$service:qa-${{ github.sha }}
        done
